#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

{%- if cookiecutter.use_postgresql == 'y' %}
if [ -z "${POSTGRES_USER:-}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 60

>&2 echo 'PostgreSQL is available'
{%- endif %}

exec "$@"
