#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

{%- if cookiecutter.use_postgresql == 'y' %}
alembic upgrade head
{%- endif %}

{%- if cookiecutter.use_opentelemetry == 'y' %}
exec opentelemetry-instrument uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
{%- else %}
exec uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
{%- endif %}
